#docker compose up -d --scale app=5
worker_processes auto; # Automatically matches available CPU cores. this is how many parallel processes nginx spawns to handle client requiests - usually the number is equal to number of cpu cores in the server

events {
    worker_connections 1024; #per worker process: how many simultaneos connections can be opened , default= 512
}

http { # http traffic - how to handle http requests
# Create a 10MB memory zone 'req_limit_zone' allowing 5 requests per second per IP
    limit_req_zone $binary_remote_addr zone=req_limit_zone:10m rate=5r/s; #`binary_remote_addr` Holds the IP address of the client making the request, 
    include mime.types; #include mime.types; tells NGINX to load a separate file named mime.types that contains a dictionary mapping file extensions (like .html, .css, .js, .png) to their official MIME types (like text/html, text/css, application/javascript, image/png).
    gzip on; #compresses text-based responses before sending them over the network, reducing payload sizes and speeding up load times.
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000; # Only compress responses larger than 1KB

    # Tell NGINX to use Docker's internal DNS server, it Tells NGINX to re-query Docker's DNS every 10 seconds to resolve the scaled 'app' containers.
    resolver 127.0.0.11 valid=10s ipv6=off;
    # Upstream block to define the Node.js backend servers for load balancing, "nodeja_cluster" is a custom name
   

    server {
        listen 443 ssl;  # Listen on port 443 for HTTPS
        server_name localhost;

        # Reads from the container mount target (/etc/nginx/certs)
        ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

        # Proxying requests 
        location / {
            # rate limit with a burst buffer of 10 requests (e.g., loading multiple page assets).
            limit_req zone=req_limit_zone burst=10 nodelay;
            # Assigning to a variable forces NGINX to re-query Docker DNS
            # and properly round-robin across all scaled 'app' containers
            set $backend_app http://app:3000;
            proxy_pass $backend_app;
         
            # Enable HTTP 1.1 for persistent upstream connections
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            # Header forwarding
            proxy_set_header Host $http_host; #Passes the original domain name/hostname requested by the client along to the Node.js backend.
            proxy_set_header X-Real-IP $remote_addr; #Sends the actual client's IP address to Node.js. Without this, the Express/Node logs would show NGINX's internal container IP as the visitor for every request.
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

          
        }
    }

    # Optional server block for HTTP to HTTPS redirection
    server {
        listen 80;  # Listen on port 80 for HTTP
        server_name localhost;

        # Redirect all HTTP requests to HTTPS on host port 8443
        location / {
            return 301 https://$host:8443$request_uri;
        }
    }
}
# 1 MB holds about 16,000 IP addresses, so 10 MB allows NGINX to track around 160,000 distinct IP addresses simultaneously for rate limiting.